import express from "express";
import { validateCoupon, createCoupon, getCoupons, deleteCoupon } from "../controllers/couponController.js";
import { protect } from "../middleware/auth.js";
import { adminOnly } from "../middleware/admin.js";
const router = express.Router();
router.post("/validate", validateCoupon);
router.get("/", protect, adminOnly, getCoupons);
router.post("/", protect, adminOnly, createCoupon);
router.delete("/:id", protect, adminOnly, deleteCoupon);
export default router;